language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: my-spa/build
  on:
    branch: main
